formatter: markdown table

sections:
  show:
    - inputs
    - outputs

settings:
  anchor: true
  default: true
  escape: true
  html: true
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
